kubycat:
  config:
  context: minikube
  namespace: elsewhere
  port: 1273
  sync:
    - name: api
      base: /home/sheldon/elsewhere/backend/api
      namespace: ""
      from:
        - config
        - fixtures
        - migrations
        - public
        - src
        - templates
        - .env
        - composer.json
        - composer.lock
        - symfony.lock
      to: /srv/api
      pod: "elsewhere-php-7845cf94cc-jzj6f"
      pod-label: tier=php
      shell: /bin/sh
    - name: dummy
      base: /home/sheldon/elsewhere/backend/dummy
      namespace: ""
      from:
        - dummy
      to: /srv/dummy
      pod: ""
      pod-label: tier=php
      shell: /bin/sh
