kubycat:
  # The Kubernetes config file to use
  config: /home/johndoe/.kube/config
  # The Kubernetes context to use
  context: minikube
  # The Kubernetes namespace to use
  # This can be specified or overridden for each individual sync
  namespace: default
  # The port to use for the kubycat file syncing server
  port: 1273
  # Individual sync configs
  sync:
    # The name of the sync
    - name: test
      # The base directory to sync from
      base: /home/johndoe/test/
      # Overridden Kubernetes options
      config: /home/johndoe/.kube/do-sfo3-k8s-johndoe
      context: do-sfo3-k8s-johndoe
      namespace: other
      # The file paths to sync
      # Note that all syncing is done recursively
      from:
        - src
        - config
        - index.php
      # The remote directory to sync into
      to: /remote/server
      # File pattern exclusions
      excluding:
        - .+~$
      including:
        - .+\.php$
      # The Kubernetes pod to sync into
      pod: pod-name
      # The Kubernetes pod label to use for finding the pod(s) to sync into
      # This can be used instead of specifying a single pod
      pod-label: key=value
      # The shell command to run in the container for deleting files
      shell: /bin/sh
      # Allows Kubycat to send desktop notifications on errors
      notify: notify-send # linux
      # notify: display notification # mac os
      # what to do on an error when executing a sync (or related command)
      # can be one of: exit (default), reload, ignore
      on-sync-error: exit
      # what to do on an error when executing a local or remote command
      # can be one of: exit (default), reload, ignore
      on-post-sync-error: exit
    - name: composer
      base: /home/johndoe/test/
      namespace: other
      from:
        - composer.json
        - composer.lock
      to: /remote/server
      pod-label: key=value
      shell: /bin/sh
      post-sync-local: composer update
      post-sync-remote: /bin/sh -c "composer install"