#! /bin/bash

# exit on errors
set -e

VERSION=$(git describe --tags --abbrev=0)

echo "This is the installer for Kubycat $VERSION."
echo ""
echo "It will guide you through the process of installing the required Perl modules, the kubycat configuration files, kubycat executables, and the Kubycat systemd service."
echo ""
echo "!!! This should work on most Linux systems without any issues, but it has only been tested on Ubuntu."
echo "!!! The systemd component will not work on MAC and should be skipped, but we're working on supporting launchd"
echo ""
echo "Please report problems on GitHub at https://github.com/sheldonjuncker/kubycat/issues"
echo ""
echo "Note: this script requires root privileges."
echo ""

# Ask if the user wants to install the Perl modules
echo -n "Install Perl modules: (y/n) "
read -r install_modules

if [ "$install_modules" = "y" ]; then
   # Ask for file path to install modules to
    echo -n "Module install path (default): "
    read -r module_path
    if [ "$module_path" != "" ]; then
        export PERL5LIB=$module_path/lib/perl5
        perl -MCPAN -eX "o conf makepl_arg INSTALL_BASE=$module_path; o conf commit"
    fi
    echo "Installing Perl modules..."
    cpan -i YAML::XS
    cpan -i IO::Socket
    cpan -i Digest::MD5
    cpan -i File::Slurp
    cpan -i Data::Dump
    cpan -i Switch

    if [ "$module_path" != "" ]; then
        echo ""
        echo "!!! For non-service use, you may need to add the following to your .bashrc file (or equivalent for Mac):"
        echo "!!! export PERL5LIB=$module_path/lib/perl5"
        echo "!!! alternatively, you can manually add the PERL5LIB=$module_path/lib/perl5 as a prefix to the kubycat script file, e.g.:"
        echo "!!! PERL5LIB=$module_path/lib/perl5 perl kubycat.pl \"\$@\""
    fi

    echo "OK -- Perl modules installed."
else
    echo "OK -- skipping module installation."
fi
echo ""

# ask for the path to the kubycat config
echo -n "Kubycat config path (/etc/kubycat): "
read -r config_path
if [ "$config_path" = "" ]; then
    config_path="/etc/kubycat"
fi
echo "Copying example config file to $config_path/config.yaml..."
sudo mkdir -p $config_path
# check if the config yaml file exists
if [ -f "$config_path/config.yaml" ]; then
    echo "INFO -- $config_path/config.yaml already exists, not overwriting"
else
    sudo cp config.example.yaml $config_path/config.yaml
fi
echo "OK -- file copied."
echo ""

# ask for the installation path for kubycat and kubycat.pl
echo -n "Kubycat install path (/usr/local/bin): "
read -r install_path
if [ "$install_path" = "" ]; then
    install_path="/usr/local/bin"
fi
echo "Copying kubycat and kubycat.pl to $install_path..."
sudo cp kubycat.pl $install_path/kubycat.pl
sudo cp kubycat $install_path/kubycat
sudo sed -i.bak "s|kubycat.pl|$install_path/kubycat.pl|" $install_path/kubycat
sudo rm $install_path/kubycat.bak
if [ "$module_path" != "" ]; then
    # add the PERLLIB5 environment variable to the beginning of the kubycat file
    KUBYCAT_TMP=`echo -n "PERL5LIB=$PERL5LIB "; cat $install_path/kubycat`
    echo "$KUBYCAT_TMP" | sudo tee $install_path/kubycat
fi
sudo chmod +x $install_path/kubycat.pl
sudo chmod +x $install_path/kubycat
echo "OK -- files copied."
echo ""


# Ask if the user wants to install the kubycat service
echo -n "Install Kubycat as a service:  (y/n) "
read -r install_service
if [ "$install_service" != "y" ]; then
    echo "OK -- service not installed."
    echo "Installation complete."
    exit 0
fi

# if linux, install the systemd service
if [[ "$OSTYPE" == "darwin"* ]]; then
  # installing the launchd service
  echo "Installing the kubycat service via launchd..."
  cp kubycat.plist kubycat.plist.tmp
  # replace the config file
  sed -i.bak "s|\$CONFIG_FILE|$config_path/config.yaml|" kubycat.service.tmp
  rm kubycat.plist.tmp.bak
  # copy the kubycat.plist file to the launchd directory
  sudo cp kubycat.plist.tmp /Library/LaunchDaemons/kubycat.plist
  rm kubycat.plist.tmp
  # enable the service
  sudo launchctl load /Library/LaunchDaemons/kubycat.plist
  # start the service
  sudo launchctl start kubycat
  # get the status
  sudo launchctl list | grep kubycat
  echo "OK -- installation complete."
else
  # update the kubycat.service file with the current user
  echo "Installing the kubycat service via systemd..."
  cp kubycat.service kubycat.service.tmp

  # replace the version
  sed -i.bak "s/\$VERSION/$VERSION/" kubycat.service.tmp

  # replace the install path
  sed -i.bak "s|\$INSTALL_PATH|$install_path|" kubycat.service.tmp

  # replace the config file
  sed -i.bak "s|\$CONFIG_FILE|$config_path/config.yaml|" kubycat.service.tmp

  rm kubycat.service.tmp.bak

  # copy the kubycat.service file to the systemd directory
  sudo cp kubycat.service.tmp /etc/systemd/user/kubycat.service
  rm kubycat.service.tmp

  # enable the service
  systemctl --user enable kubycat

  # reload the systemd daemon
  systemctl --user daemon-reload

  # start the service
  systemctl --user start kubycat
  echo "OK -- service installed."

  # done
  echo "Getting kubycat status..."
  systemctl --user status kubycat
  echo "OK -- installation complete."
fi